run = "forever"

[tools.pylint]
config = "{affected_targets}"
# top level python files and anything under plugger, but not the example files.
target_paths = "*.py plugger/**/*.py"
trigger_paths = ".pylintrc"
preconditions = []

#[tools.vulture]
#config = "."
#trigger_paths = "**/*.py"

#[tools.dodgy]
#trigger_paths = "**/*.py"

[tools.flake8]
config = "{affected_targets}"
target_paths = "**/*.py"
trigger_paths = ".flake8"

#[tools.pytest]
## config = [
##     "--cov", "{target_paths}",
##     "--no-cov-on-fail",
##     "--cov-fail-under=100",
##     "--cov-branch",
##     "--cov-report", "term-missing",
##     "{target_paths}",
## ]
#config = "{affected_targets}"
#target_paths = "**/test*.py"
#trigger_paths = "**/*.py"
#preconditions = ['pylint', 'vulture', 'flake8', 'dodgy']

# [tools.mypy]
# config = [
#     "--strict",
#     "--ignore-missing-imports",
#     "--custom-typeshed-dir", "/Users/joe/repos/third-party/typeshed/",
#     "{changed_target_paths}",
# ]
# target_paths = [ "setup.py", "pocketwalk.py", "test_pocketwalk.py",]
